stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: alpine:edge
  before_script:
    - apk add npm git tar
    - npm ci
  script:
    - echo $CI_COMMIT_SHA > version
    - tar -cf app.tar --exclude-vcs --exclude=app.tar .
  artifacts:
    paths:
      - app.tar

build-mcc:
  stage: build
  image: alpine:edge
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
    - apk add mono git
    - git clone https://github.com/ORelio/Minecraft-Console-Client
  script:
    - cd Minecraft-Console-Client
    - xbuild MinecraftClient.sln
    - cp MinecraftClient/bin/Debug/MinecraftClient.exe ../
  artifacts:
    paths:
      - MinecraftClient.exe

build-lang:
  stage: build
  image: alpine:edge
  before_script:
    - apk add jq
  script:
    - ./mcc_download_new_lang.sh zh_tw
  artifacts:
    paths:
      - lang/zh_TW.lang

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:production
  only:
    - master

deploy:
  stage: deploy
  image:
    name: alpine:latest
  variables:
    GIT_STRATEGY: none
  environment:
    name: production
  before_script:
    - apk add gettext
    - wget https://storage.googleapis.com/kubernetes-release/release/v1.17.9/bin/linux/amd64/kubectl
    - chmod +x kubectl
  script:
    - ./kubectl -n $KUBE_NAMESPACE create secret generic ${CI_PROJECT_PATH_SLUG}-secrets --from-file=token=$TOKEN --dry-run -o yaml | ./kubectl -n $KUBE_NAMESPACE apply -f -
    - ./kubectl -n $KUBE_NAMESPACE create configmap ${CI_PROJECT_PATH_SLUG}-configs --from-file=ip=$IP --from-file=mcc-conf=$MCC_CONF --dry-run -o yaml | ./kubectl -n $KUBE_NAMESPACE apply -f -
    - ./kubectl -n $KUBE_NAMESPACE create configmap ${CI_PROJECT_PATH_SLUG}-langs --from-file=zh_TW.lang=lang/zh_TW.lang --dry-run -o yaml | ./kubectl -n $KUBE_NAMESPACE apply -f -
    - envsubst < deployment.yml > out.yml
    - ./kubectl -n $KUBE_NAMESPACE apply -f out.yml
