apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-mcc-bot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: discord-mcc-bot
          image: registry.eglo.ga/none
          volumeMounts:
            - name: secrets
              mountPath: /srv/token
              subPath: token
            - name: configs
              mountPath: /srv/ip
              subPath: ip
            - name: configs
              mountPath: /srv/MinecraftClient.ini
              subPath: mcc-conf
            - name: langs
              mountPath: /srv/lang
      volumes:
        - name: secrets
          secret:
            secretName: secrets
        - name: configs
          configMap:
            name: configs
        - name: langs
          configMap:
            name: langs
